README.md
Small change to content listing, including incident management
Kansa Powershell Framework
Request Tracker for Incident Response
Fast Evidence Collector Toolkit
=> Kansa, RTIR, FECT added

README.md
Added + linked data collection category of tools
Moved FECT + PSRecon
Added FastIR Collector from https://github.com/meirwah/awesome-incident-response/pull/14
=> Data Collection Category

README.md
AChoir Windows IR Collection Utilities Framework
DumpIt Windows Memory Dump Creator
=> AChoir + DumpIt

README.md
Added misc information I have found useful
-Highlighter from Fire/Mandiant
-RegRipper Registry tool for win forensics
-OSX Evidence Section
-Sandboxing/reversing tools (both local and online)
-Book Section with Amazon link (feel free to change)
=> Adding content to Win forensics and other tools; Adding sections for OSX forensics,Sandboxing/reversing and Books

README.md
=> Memoryze by Mandiant

README.md
I think osxcollector would be a valuable addition to this repo!
=> osxcollector because it's awesome

README.md
Also fix the link to VirusTotal (https://virustotal.com doesn't resolve without www.)
=> Update URLs based on redirects

README.md
=> Update Readme.md - Added Triage-IR

README.md
Adding Fenrir and bulk_extractor to the mix.
Stenographer added on the 9th.
I noticed there's no specific Linux collection category, so I added bulk_extractor to other tools. This (and others) the tools (do | may) support multi platform though. Any thoughts about this?
=> Fenrir + bulk_extractor

README.md
=> Add Evidence collectors section

README.md
=> FastIR for Linux + Linux Evidence Collection category

README.md
to Windows Evidence Collection
=> Adding PowerForensics

README.md
=> Adding KonckKnock

README.md
added a new tool called Lorg: a tool for advanced HTTPD logfile security analysis and forensics
=> Lorg tool added

README.md
to https://www.incidentresponse.com/playbooks/
fixes #59
=> update playbooks link

README.md
=> Adding LiME

README.md
Adding Zentral to  All in one Tools
=> Adding Zentral

README.md
Link to my new memory analysis platform ;)
=> Added inVtero.net

README.md
Add Demisto free edition to incident mgmt section
=> Add Demisto to incident mgmt section

README.md
=> Adding IRM

README.md
=> add VolDiff

README.md
PR for adding Metadefender Cloud to list of Sandboxing/reversing tools
=> Add Metadefender Cloud

README.md
And move sqhunter to turn the list into alphabetical order again
=> Add DumpsterFire

README.md
Please consider adding Etsy's morgue tool for managing postmortem data. Thank you!
=> Add morgue by etsy

README.md
Please add Bitscout as a trustable remote forensics and acquisition livecd builder tool! Thank you
=> Add Bitscout

README.md
=> adding helk

README.md
Scott Roberts DFIR Intro link is broken, pointed to his Medium post on the same topic
=> Fix Books section DFIR Intro link

README_ch.md
Update Chinese version as per the latest English version.
Replace the "," with "，" to make it.
=> Update the Chinese version as per the latest English version

README.md
Add logdissect log analysis tool (CLI/Python API) to "Log Analysis Tools" section.
=> Add logdissect log analysis tool (CLI/Python API)

README.md
The tool has matured and is now multithreaded for extra oomph!
=> Added PyaraScanner

README.md
Adds Kaspersky CyberTrace and Kaspersky Threat Intelligence Portal
=> Add Kaspersky Threat Intelligence 

README.md
=> Add CAPE sandbox

README.md
I just added some tools I frequently use during IR engagements.
=> Add some tools

README.md
Hey @meirwah 
just fixing the "Memoryze" link.
Cheers!
=> Fixing Memoryze link

README.md
UAC tool added to the Evidence Collection list.
Signed-off-by: Thiago Lahr <tclahr@br.ibm.com>
=> UAC tool added

README.md
UAC tool description updated.
Signed-off-by: Thiago Canozzo Lahr <tclahr@br.ibm.com>
=> upd: UAC tool description updated

README.md
New proposal with a  SandBox Tool
=> New Tool Proposal

README.md
Using a well-conceived incident response plan in the aftermath of an online security breach enables your team to identify attackers and learn how they operate. But, only when you approach incident response with a cyber threat intelligence mindset will you truly understand the value of that information. With this practical guide, you’ll learn the fundamentals of intelligence analysis, as well as the best ways to incorporate these techniques into your incident response process.
=> Book: Intelligence-Driven Incident Response

README.md
Hi. 
I've added two new tools under the Log Analysis tools:
- Log Parser Lizard
- Event Log Observer
Please review the change
Thanks
=> Log Parser Lizard na Event Log Observer are added to the list

README.md
A tool to view the events in Apple Endpoint Security Framework (ESF) in real time.
=> Adding The ESF Playground

README.md
Since no update happened in PR #179 for the last two and a half months, I adjusted and added that.
=> Added Awesome Event IDs (re-submit)

README.md
Added Orochi, a framework for memory dump analysis.
=> Added Orochi

README.md
Added Catalyst, a SOAR and incident management system
=> Add Catalyst

README.md
Added Cahinsaw log analysis tool.
=> Added Cahinsaw log analysis tool.

README.md
Added a couple of books related DFIR.
=> Added a couple of books

README.md
fixes https://github.com/meirwah/awesome-incident-response/issues/191
=> remove augmentd.co

README.md
Update UAC tool description.
Signed-off-by: Thiago Canozzo Lahr <tclahr@br.ibm.com>
=> upd: update UAC tool description

README.md
=> Added WELA logs analyzer.

README.md
Added Hayabusa log analysis tool
=> Added Hayabusa log analysis tool

README.md, README_ch.md
- update cyphon link in README_ch.md
- update cyphon link in README.md
=> Update dead links in Readme

README.md
=> Add Matano

README.md
Added Zenduty under Incident Management and the Site Reliability Slack community under Communities
=> Added Zenduty in Incident Management and SRE Slack

README.md
A must read for DFIR personnel.
=> Added the Art of Memory Forensics

README.md
entries added for Linux and Windows versions of DumpIt
=> Add entries for MAGNET DumpIt

README.md
For more information: https://docs.dissect.tools/en/latest/
=> Add Dissect and Acquire

README.md
Tool for acquire, triage and investigate remote evidence via portable iSCSI readonly access
=> Add SPECTR3

README.md
**[MemProcFS]** (https://github.com/ufrisk/MemProcFS) - MemProcFS is an easy and convenient way of viewing physical memory as files in a virtual file system.
=> added MemProcFS under Memory Analysis Tools

.github/workflows/check_urls.yml, .github/workflows/lint_readme.yml, README.md, README_ch.md
Hi Meir!
The following things are done with this PR:
- added a GitHub Workflow that checks all URLs on every push and PR (5sec timout, 3 retries)
- added a cron schedule to execute the Workflow every saturday morning (around 5:30 am UTC)
- updated some links, fixed one broken link and removed deprecated links
- added a status badge (might show an error on first glance because the badge only becomes valid once the PR has been merged and the workflow has been run in the original repo for the first time)
Happy hunting!
stuhli
=> GitHub Workflow that checks all URLs

README.md, README_ch.md
remove inactive links in README.md
uppdate of chinese translation
=> Update of README/README_ch.md
